=== nattadasu/initApps/schema/pkgs.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "id": {
                "description": "The unique identifier for the package, formatted in tld.company.appname",
                "type": "string"
            },
            "name": {
                "type": "string"
            },
            "publisher": {
                "type": "string"
            },
            "author": {
                "oneOf": [
                    {
                        "type": "string"
                    },
                    {
                        "type": "array",
                        "uniqueItems": true
                    }
                ]
            },
            "description": {
                "type": "string"
            },
            "homepage": {
                "type": "string"
            },
            "license": {
                "type": "string"
            },
            "available": {
                "type": "array",
                "contains": {
                    "type": "string",
                    "enum": ["Windows", "Linux", "macOS","Android"]
                },
                "uniqueItems": true
            },
            "packages": {
                "type": "object",
                "properties": {
                    "windows": {
                        "type": "object",
                        "properties": {
                            "winget": {
                                "oneOf": [
                                    {
                                        "type": "string",
                                        "pattern": "^[a-zA-Z0-9\\-\\+]+\\.[a-zA-Z0-9\\-\\+!]+(\\.[a-zA-Z0-9\\.]+)?$"
                                    },
                                    {
                                        "type": "null"
                                    }
                                ]
                            },
                            "choco": {
                                "oneOf": [
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "type": "null"
                                    }
                                ]
                            },
                            "scoop": {
                                "oneOf": [
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "type": "null"
                                    }
                                ]
                            },
                            "bin": {
                                "oneOf": [
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "type": "null"
                                    }
                                ]
                            }
                        },
                        "additionalProperties": false
                    },
                    "linux": {
                        "type": "object",
                        "additionalProperties": false,
                        "properties": {
                            "apt": {
                                "oneOf": [
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "type": "null"
                                    }
                                ]
                            },
                            "snap": {
                                "oneOf": [
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "type": "null"
                                    }
                                ]
                            },
                            "flatpak": {
                                "oneOf": [
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "type": "null"
                                    }
                                ]
                            },
                            "bin": {
                                "oneOf": [
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "type": "null"
                                    }
                                ]
                            },
                            "debGet": {
                                "oneOf": [
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "type": "null"
                                    }
                                ]
                            },
                            "pacstall": {
                                "oneOf": [
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "type": "null"
                                    }
                                ]
                            },
                            "dnf": {
                                "oneOf": [
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "type": "null"
                                    }
                                ]
                            },
                            "apk": {
                                "oneOf": [
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "type": "null"
                                    }
                                ]
                            },
                            "appimage": {
                                "oneOf": [
                                    {
                                        "type": "string",
                                        "format": "uri"
                                    },
                                    {
                                        "type": "null"
                                    }
                                ]
                            },
                            "aur": {
                                "oneOf": [
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "type": "null"
                                    }
                                ]
                            },
                            "nixpkgs": {
                                "oneOf": [
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "type": "null"
                                    }
                                ]
                            },
                            "brew": {
                                "oneOf": [
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "type": "null"
                                    }
                                ]
                            }
                        }
                    },
                    "android": {
                        "type": "object",
                        "additionalProperties": false,
                        "properties": {
                            "pkg": {
                                "oneOf": [
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "type": "null"
                                    }
                                ]
                            },
                            "play" : {
                                "oneOf": [
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "type": "null"
                                    }
                                ]
                            },
                            "bin": {
                                "oneOf": [
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "type": "null"
                                    }
                                ]
                            }
                        }
                    }
                },
                "additionalProperties": false
            }
        },
        "additionalProperties": false
    },
    "uniqueItems": true
}

=== nattadasu/initApps/data/pkgs.json
[
  {
    "id": "org.7-zip.7-Zip",
    "name": "7-Zip",
    "publisher": "Igor Pavlov",
    "author": "Igor Pavlov",
    "homepage": "https://www.7-zip.org",
    "license": "LGPL",
    "available": [
      "Windows"
    ],
    "packages": {
      "windows": {
        "choco": "7zip",
        "scoop": null,
        "winget": "7zip.7zip"
      },
      "linux": {
        "apk": null,
        "appimage": null,
        "apt": null,
        "aur": null,
        "brew": null,
        "debGet": null,
        "dnf": null,
        "flatpak": null,
        "nixpkgs": null,
        "pacstall": null,
        "snap": null
      },
      "android": {
        "pkg": null,
        "play": null
      }
    }
  },
  {
    "id": "ru.aimp.AIMP",
    "name": "AIMP",
    "publisher": "AIMP DevTeam",
    "author": "Artem Izmaylov",
    "homepage": "https://www.aimp.ru",
    "license": "Proprietary",
    "available": [
      "Windows",
      "Android"
    ],
    "packages": {
      "windows": {
        "choco": "aimp",
        "scoop": "aimp",
        "winget": "AIMP.AIMP"
      },
      "linux": {
        "apk": null,
        "appimage": null,
        "apt": null,
        "aur": null,
        "brew": null,
        "debGet": null,
        "dnf": null,
        "flatpak": null,
        "nixpkgs": null,
        "pacstall": null,
        "snap": null
      },
      "android": {
        "pkg": null,
        "play": "com.aimp.player"
      }
    }
  },
  {
    "id": "com.aomeitech.PartitionAssistant",
    "name": "AOMEI Partition Assistant",
    "publisher": "AOMEI International Network Limited.",
    "author": "AOMEI International Network Limited.",
    "homepage": "https://www.aomeitech.com/aomei-partition-assistant.html",
    "license": "Proprietary",
    "available": [
      "Windows"
    ],
    "packages": {
      "windows": {
        "choco": "partition-assistant-standard",
        "scoop": null,
        "winget": "AOMEI.PartitionAssistant"
      },
      "linux": {
        "apk": null,
        "appimage": null,
        "apt": null,
        "aur": null,
        "brew": null,
        "debGet": null,
        "dnf": null,
        "flatpak": null,
        "nixpkgs": null,
        "pacstall": null,
        "snap": null
      },
      "android": {
        "pkg": null,
        "play": null
      }
    }
  },
  {
    "id": "org.audacityteam.Audacity",
    "name": "Audacity",
    "publisher": "Audacity Team",
    "author": "Audacity Team",
    "homepage": "https://www.audacityteam.org/",
    "license": "GPL-2.0-or-later",
    "available": [
      "Windows",
      "Linux"
    ],
    "packages": {
      "windows": {
        "choco": "audacity",
        "scoop": "audacity",
        "winget": "Audacity.Audacity"
      },
      "linux": {
        "apk": "audacity",
        "appimage": null,
        "apt": "audacity",
        "aur": "audacity-git",
        "brew": null,
        "debGet": null,
        "dnf": "audacity",
        "flatpak": "org.audacityteam.Audacity",
        "nixpkgs": "audacity",
        "pacstall": null,
        "snap": "audacity"
      },
      "android": {
        "pkg": null,
        "play": null
      }
    }
  },
  {
    "id": "com.autohotkey.AutoHotkey",
    "name": "AutoHotkey",
    "publisher": "Lexikos",
    "author": "Steve Gray",
    "homepage": "https://autohotkey.com",
    "license": "GPL-2.0",
    "available": [
      "Windows"
    ],
    "packages": {
      "windows": {
        "choco": "autohotkey",
        "scoop": "autohotkey",
        "winget": "Lexikos.AutoHotkey"
      },
      "linux": {
        "apk": null,
        "appimage": null,
        "apt": null,
        "aur": null,
        "brew": null,
        "debGet": null,
        "dnf": null,
        "flatpak": null,
        "nixpkgs": null,
        "pacstall": null,
        "snap": null
      },
      "android": {
        "pkg": null,
        "play": null
      }
    }
  },
  {
    "id": "io.balena.Etcher",
    "name": "balenaEtcher",
    "publisher": "Balena Inc.",
    "author": "Balena Inc.",
    "homepage": "https://www.balena.io/etcher",
    "license": "Apache License 2.0",
    "available": [
      "Windows",
      "Linux"
    ],
    "packages": {
      "windows": {
        "choco": "etcher",
        "scoop": null,
        "winget": "Balena.Etcher"
      },
      "linux": {
        "apk": null,
        "appimage": null,
        "apt": null,
        "aur": null,
        "brew": null,
        "debGet": "balena-etcher-electron",
        "dnf": null,
        "flatpak": null,
        "nixpkgs": null,
        "pacstall": null,
        "snap": null
      },
      "android": {
        "pkg": null,
        "play": null
      }
    }
  },
  {
    "id": "eu.betterbird.Betterbird",
    "name": "Betterbird",
    "publisher": "Betterbird-Team",
    "author": "Betterbird-Team",
    "homepage": "https://betterbird.eu",
    "license": "MPL-2.0",
    "available": [
      "Windows",
      "Linux"
    ],
    "packages": {
      "windows": {
        "choco": "betterbird",
        "scoop": null,
        "winget": "Betterbird.Betterbird"
      },
      "linux": {
        "apk": null,
        "appimage": null,
        "apt": null,
        "aur": "betterbird-bin",
        "brew": null,
        "debGet": null,
        "dnf": null,
        "flatpak": "eu.betterbird.Betterbird",
        "nixpkgs": null,
        "pacstall": null,
        "snap": null
      },
      "android": {
        "pkg": null,
        "play": null
      }
    }
  },
  {
    "id": "com.bitwarden.Bitwarden",
    "name": "Bitwarden",
    "publisher": "Bitwarden Inc.",
    "author": "Bitwarden Inc.",
    "homepage": "https://bitwarden.com/download/",
    "license": "GPL-3.0 or Bitwarden-1.0",
    "available": [
      "Windows",
      "Linux",
      "Android"
    ],
    "packages": {
      "windows": {
        "choco": "bitwarden",
        "scoop": "bitwarden",
        "winget": "Bitwarden.Bitwarden"
      },
      "linux": {
        "apk": null,
        "appimage": null,
        "apt": null,
        "aur": "bitwarden-git",
        "brew": null,
        "debGet": "bitwarden",
        "dnf": null,
        "flatpak": "com.bitwarden.desktop",
        "nixpkgs": "bitwarden",
        "pacstall": "bitwarden-deb",
        "snap": "bitwarden"
      },
      "android": {
        "pkg": null,
        "play": "com.x8bit.bitwarden"
      }
    }
  },
  {
    "id": "com.brave.Browser",
    "name": "Brave",
    "publisher": "Brave Software Inc",
    "author": "Brave Software, Inc.",
    "homepage": "https://brave.com/download/",
    "license": "MPL-2.0",
    "available": [
      "Windows",
      "Linux",
      "Android"
    ],
    "packages": {
      "windows": {
        "choco": "brave",
        "scoop": "brave",
        "winget": "Brave.Brave"
      },
      "linux": {
        "apk": null,
        "appimage": null,
        "apt": null,
        "aur": null,
        "brew": null,
        "debGet": "brave",
        "dnf": null,
        "flatpak": "com.brave.Browser",
        "nixpkgs": null,
        "pacstall": null,
        "snap": null
      },
      "android": {
        "pkg": null,
        "play": "com.brave.browser"
      }
    }
  },
  {
    "id": "com.calibre_ebook.calibre",
    "name": "calibre",
    "publisher": "Kovid Goyal",
    "author": "Kovid Goyal",
    "homepage": "https://calibre-ebook.com/",
    "license": "GPL-3.0-only",
    "available": [
      "Windows",
      "Linux"
    ],
    "packages": {
      "windows": {
        "choco": "calibre",
        "scoop": "calibre",
        "winget": "calibre.calibre"
      },
      "linux": {
        "apk": null,
        "appimage": null,
        "apt": null,
        "aur": null,
        "brew": null,
        "debGet": null,
        "dnf": null,
        "flatpak": "com.calibre_ebook.calibre",
        "nixpkgs": null,
        "pacstall": null,
        "snap": null
      },
      "android": {
        "pkg": null,
        "play": null
      }
    }
  },
  {
    "id": "io.github.chrisant996.Clink",
    "name": "Clink",
    "publisher": "Christopher Antos",
    "author": "Chris Antos",
    "homepage": "https://chrisant996.github.io/clink/",
    "license": "GPL-3.0",
    "available": [
      "Windows"
    ],
    "packages": {
      "windows": {
        "choco": "clink",
        "scoop": "clink",
        "winget": "chrisant996.Clink"
      },
      "linux": {
        "apk": null,
        "appimage": null,
        "apt": null,
        "aur": null,
        "brew": null,
        "debGet": null,
        "dnf": null,
        "flatpak": null,
        "nixpkgs": null,
        "pacstall": null,
        "snap": null
      },
      "android": {
        "pkg": null,
        "play": null
      }
    }
  },
  {
    "id": "com.cloudflare.warp",
    "name": "Cloudflare WARP",
    "publisher": "Cloudflare, Inc.",
    "author": "Cloudflare, Inc.",
    "homepage": "https://one.one.one.one/",
    "license": "Proprietary",
    "available": [
      "Windows",
      "Android"
    ],
    "packages": {
      "windows": {
        "choco": "warp",
        "scoop": null,
        "winget": "Cloudflare.Warp"
      },
      "linux": {
        "apk": null,
        "appimage": null,
        "apt": null,
        "aur": null,
        "brew": null,
        "debGet": null,
        "dnf": null,
        "flatpak": null,
        "nixpkgs": null,
        "pacstall": null,
        "snap": null
      },
      "android": {
        "pkg": null,
        "play": "com.cloudflare.onedotonedotonedotone"
      }
    }
  },
  {
    "id": "se.curl.cURL",
    "name": "curl",
    "publisher": "cURL project",
    "author": "Daniel Stenberg",
    "homepage": "https://curl.se/",
    "license": "curl",
    "available": [
      "Windows",
      "Linux"
    ],
    "packages": {
      "windows": {
        "choco": "curl",
        "scoop": "curl",
        "winget": null
      },
      "linux": {
        "apk": "curl",
        "appimage": null,
        "apt": "curl",
        "aur": "curl",
        "brew": null,
        "debGet": null,
